apiVersion: v1
kind: Namespace
metadata:
  name: bk

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bk
  labels:
    app: points
  name: points
spec:
  selector:
    matchLabels:
      app: points
  template:
    metadata:
      labels:
        app: points
    spec:
      containers:
        - image: gcr.io/pgtm-jlong/points
          imagePullPolicy: Always
          name: points

